# Generated by Django 2.0 on 2018-08-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_long', models.CharField(max_length=250, unique=True)),
                ('url_short', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
